name: generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=6366F1,8B5CF6,3B82F6,22D3EE&color_dots=161B22,30363D,6366F1,8B5CF6,22D3EE
            dist/github-contribution-grid-snake-dark.svg?color_snake=6366F1,8B5CF6,3B82F6,22D3EE&color_dots=0A0E1A,30363D,6366F1,8B5CF6,22D3EE

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
